-- Generated by tests/schema.test.ts from the migrations. Do not edit.

-- Vocabularies. Each is a table, vocab_<name> (word TEXT PRIMARY KEY), holding these words:
-- actor_kind: person, agent, system
-- repository_access: read, write, observe
-- location_kind: existing, managed
-- location_state: ready, needs_access, changed, unavailable
-- artifact_kind: brief, message, transcript, patch, log, report, findings, summary, other
-- sensitivity: normal, may_contain_secrets
-- task_state: draft, open, done, abandoned
-- plan_state: proposed, accepted, replaced, declined
-- run_state: admitted, running, suspended, succeeded, failed, cancelled
-- run_attempt_state: active, succeeded, failed, cancelled, interrupted
-- workspace_state: preparing, ready, published, cleaned, failed
-- snapshot_reason: node_started, node_ended, switch, interrupt
-- execution_state: running, succeeded, failed, cancelled
-- graph_revision_cause: materialized, patch
-- node_type: deterministic_action, agent, integration, human_decision, condition, bounded_map, join, verification, compensation, subworkflow, bounded_loop
-- node_state: pending, ready, running, succeeded, failed, skipped, cancelled, uncertain
-- node_attempt_state: ready, admitted, running, waiting_attention, verifying, succeeded, failed, cancelling, cancelled, uncertain, reconciling, held, superseded
-- hold_reason: usage_limit, agent_unavailable
-- thread_kind: coordinator, task, step
-- thread_item_kind: user_message, agent_message, agent_thought, tool_call, plan, step_result, notice, task, arrival
-- input_disposition: after_current, interrupt_and_continue, supersede_pending, cancel_run
-- user_input_state: queued, delivered, superseded
-- turn_delivery_state: pending, delivered, completed, interrupted, interruption_uncertain, failed
-- installation_status: supported, degraded, blocked, missing
-- auth_mode: vendor_cli, api_key, oauth, enterprise, workload
-- account_state: ok, warning, limited
-- account_status_source: error, side_channel
-- provider_session_state: probing, auth_required, ready, starting, active, waiting_approval, completed, cancelling, cancelled, lost, reconciling, uncertain, failed, superseded
-- process_purpose: agent, verify, setup, git, other, probe
-- process_state: launching, running, exited, killed, unknown
-- tool_kind: read, edit, delete, move, search, execute, think, fetch, switch_mode, other
-- permission_request_state: open, decided, cancelled
-- attention_kind: permission, question, stuck, plan, graph_patch, usage_limit, review_disagreement
-- attention_state: open, answered, expired, withdrawn
-- finding_severity: blocking, major, minor, nit
-- finding_state: open, fixed, set_aside, dismissed
-- decision_outcome: allow, reject, answer, fix, dismiss
-- decision_scope: once, rule, turn
-- change_set_state: open, published, abandoned
-- pull_request_state: none, draft, ready, merged, closed
-- work_item_state: pending, claimed, done, failed, uncertain
-- mutation_state: intended, confirmed, failed, uncertain
-- aggregate_type: project, task, task_plan, run, run_attempt, workspace, workflow_execution, node, node_attempt, thread, user_input, turn_delivery, provider_session, permission_request, attention_request, decision, finding, change_set, mutation_receipt, agent_installation, account_status, thread_item, connection, external_link, policy, agent_account
-- connection_product: github, gitlab, bitbucket_cloud, bitbucket_dc, linear, jira_cloud, jira_dc, trello
-- connection_auth: device_flow, pkce, token
-- connection_state: ready, reauth_required, removed
-- external_kind: issue, change

CREATE TABLE "schema_migrations" (
  migration_id integer PRIMARY KEY NOT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE devices (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'dev_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  name TEXT NOT NULL,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE actors (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'act_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  kind TEXT NOT NULL REFERENCES vocab_actor_kind (word),
  display_name TEXT NOT NULL,
  agent_id TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  CHECK ((kind = 'agent') = (agent_id IS NOT NULL))
) STRICT;

CREATE TABLE runtime_instances (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 3) = 'rt_' AND length(id) = 35 AND substr(id, 4) NOT GLOB '*[^0-9a-f]*'),
  device_id TEXT NOT NULL REFERENCES devices (id),
  pid INTEGER NOT NULL CHECK (pid > 0),
  app_version TEXT NOT NULL,
  started_at TEXT NOT NULL CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE projects (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'proj_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE CHECK (slug <> '' AND slug NOT GLOB '*[^a-z0-9-]*'),
  created_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  archived_at TEXT CHECK (archived_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE policies (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'pol_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  revision INTEGER NOT NULL CHECK (revision >= 1),
  rules TEXT NOT NULL CHECK (json_valid(rules)),
  created_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (project_id, revision),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE project_settings (
  project_id TEXT PRIMARY KEY NOT NULL REFERENCES projects (id),
  setup_command TEXT,
  check_command TEXT,
  copy_files TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(copy_files)),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE device_project_settings (
  project_id TEXT NOT NULL REFERENCES projects (id),
  device_id TEXT NOT NULL REFERENCES devices (id),
  worktree_root TEXT,
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (project_id, device_id)
) STRICT;

CREATE TABLE repository_bindings (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'repo_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  slug TEXT NOT NULL CHECK (slug <> '' AND slug NOT GLOB '*[^a-z0-9-]*'),
  role TEXT NOT NULL,
  display_name TEXT NOT NULL,
  remote_fingerprints TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(remote_fingerprints)),
  provider_repository_id TEXT,
  allowed_subpaths TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(allowed_subpaths)),
  default_base_ref TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  detached_at TEXT CHECK (detached_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (project_id, slug),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE repository_locations (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'loc_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  binding_id TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES devices (id),
  kind TEXT NOT NULL REFERENCES vocab_location_kind (word),
  path TEXT NOT NULL,
  observed_remotes TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(observed_remotes)),
  state TEXT NOT NULL REFERENCES vocab_location_state (word),
  verified_at TEXT CHECK (verified_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (binding_id, device_id),
  FOREIGN KEY (binding_id, project_id) REFERENCES repository_bindings (id, project_id)
) STRICT;

CREATE TABLE artifacts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'art_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'),
  size INTEGER NOT NULL CHECK (size >= 0),
  media_type TEXT NOT NULL,
  kind TEXT NOT NULL REFERENCES vocab_artifact_kind (word),
  sensitivity TEXT NOT NULL DEFAULT 'normal' REFERENCES vocab_sensitivity (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE artifact_links (
  project_id TEXT NOT NULL REFERENCES projects (id),
  artifact_id TEXT NOT NULL,
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  role TEXT NOT NULL,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (artifact_id, subject_type, subject_id, role),
  FOREIGN KEY (artifact_id, project_id) REFERENCES artifacts (id, project_id)
) STRICT;

CREATE INDEX repository_bindings_by_project ON repository_bindings (project_id);

CREATE INDEX artifacts_by_digest ON artifacts (sha256);

CREATE INDEX artifact_links_by_subject ON artifact_links (subject_type, subject_id);

CREATE TABLE tasks (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'task_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  slug TEXT NOT NULL CHECK (slug <> '' AND slug NOT GLOB '*[^a-z0-9-]*'),
  state TEXT NOT NULL REFERENCES vocab_task_state (word),
  created_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  settled_at TEXT CHECK (settled_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (project_id, slug),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE task_repository_requirements (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'req_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT NOT NULL,
  binding_id TEXT NOT NULL,
  access TEXT NOT NULL REFERENCES vocab_repository_access (word),
  allowed_roots TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(allowed_roots)),
  base_ref TEXT,
  required INTEGER NOT NULL DEFAULT 1 CHECK (required IN (0, 1)),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (task_id, binding_id),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  FOREIGN KEY (binding_id, project_id) REFERENCES repository_bindings (id, project_id)
) STRICT;

CREATE TABLE workflow_definitions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'wdef_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  name TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  retired_at TEXT CHECK (retired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE workflow_versions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'wver_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  definition_id TEXT NOT NULL REFERENCES workflow_definitions (id),
  version INTEGER NOT NULL CHECK (version >= 1),
  content_hash TEXT NOT NULL CHECK (length(content_hash) = 64 AND content_hash NOT GLOB '*[^0-9a-f]*'),
  definition TEXT NOT NULL CHECK (json_valid(definition)),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (definition_id, version)
) STRICT;

CREATE TABLE task_plans (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'plan_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT NOT NULL,
  workflow_version_id TEXT NOT NULL REFERENCES workflow_versions (id),
  parameters TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(parameters)),
  proposed_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  state TEXT NOT NULL REFERENCES vocab_plan_state (word),
  proposed_at TEXT NOT NULL CHECK (proposed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  starts_at TEXT CHECK (starts_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  decided_at TEXT CHECK (decided_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE runs (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'run_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT NOT NULL,
  plan_id TEXT,
  workflow_version_id TEXT NOT NULL REFERENCES workflow_versions (id),
  policy_id TEXT NOT NULL,
  parameters TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(parameters)),
  budget TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(budget)),
  state TEXT NOT NULL REFERENCES vocab_run_state (word),
  end_reason TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  FOREIGN KEY (plan_id, project_id) REFERENCES task_plans (id, project_id),
  FOREIGN KEY (policy_id, project_id) REFERENCES policies (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE run_repository_requirements (
  project_id TEXT NOT NULL REFERENCES projects (id),
  run_id TEXT NOT NULL,
  binding_id TEXT NOT NULL,
  access TEXT NOT NULL REFERENCES vocab_repository_access (word),
  allowed_roots TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(allowed_roots)),
  base_ref TEXT,
  required INTEGER NOT NULL DEFAULT 1 CHECK (required IN (0, 1)),
  PRIMARY KEY (run_id, binding_id),
  FOREIGN KEY (run_id, project_id) REFERENCES runs (id, project_id),
  FOREIGN KEY (binding_id, project_id) REFERENCES repository_bindings (id, project_id)
) STRICT;

CREATE TABLE run_attempts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'ratt_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  run_id TEXT NOT NULL,
  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
  device_id TEXT NOT NULL REFERENCES devices (id),
  controller_generation INTEGER NOT NULL DEFAULT 1 CHECK (controller_generation >= 1),
  controller_instance_id TEXT NOT NULL REFERENCES runtime_instances (id),
  state TEXT NOT NULL REFERENCES vocab_run_attempt_state (word),
  started_at TEXT NOT NULL CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (run_id, attempt_number),
  FOREIGN KEY (run_id, project_id) REFERENCES runs (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE workspaces (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 3) = 'ws_' AND length(id) = 35 AND substr(id, 4) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT NOT NULL,
  binding_id TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES devices (id),
  access TEXT NOT NULL REFERENCES vocab_repository_access (word),
  path TEXT NOT NULL,
  base_ref TEXT NOT NULL,
  base_commit TEXT CHECK (length(base_commit) IN (40, 64) AND base_commit NOT GLOB '*[^0-9a-f]*'),
  branch TEXT NOT NULL,
  state TEXT NOT NULL REFERENCES vocab_workspace_state (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  cleaned_at TEXT CHECK (cleaned_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (task_id, binding_id, device_id),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  FOREIGN KEY (binding_id, project_id) REFERENCES repository_bindings (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE workflow_executions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'wexe_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  run_id TEXT NOT NULL UNIQUE,
  workflow_version_id TEXT NOT NULL REFERENCES workflow_versions (id),
  graph_revision INTEGER NOT NULL DEFAULT 1 CHECK (graph_revision >= 1),
  state TEXT NOT NULL REFERENCES vocab_execution_state (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  FOREIGN KEY (run_id, project_id) REFERENCES runs (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE execution_graph_revisions (
  project_id TEXT NOT NULL REFERENCES projects (id),
  execution_id TEXT NOT NULL,
  revision INTEGER NOT NULL CHECK (revision >= 1),
  graph TEXT NOT NULL CHECK (json_valid(graph)),
  cause TEXT NOT NULL REFERENCES vocab_graph_revision_cause (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (execution_id, revision),
  FOREIGN KEY (execution_id, project_id) REFERENCES workflow_executions (id, project_id)
) STRICT;

CREATE TABLE nodes (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'node_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  execution_id TEXT NOT NULL,
  node_key TEXT NOT NULL,
  iteration INTEGER NOT NULL DEFAULT 0 CHECK (iteration >= 0),
  type TEXT NOT NULL REFERENCES vocab_node_type (word),
  added_in_revision INTEGER NOT NULL CHECK (added_in_revision >= 1),
  config TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(config)),
  state TEXT NOT NULL REFERENCES vocab_node_state (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (execution_id, node_key, iteration),
  FOREIGN KEY (execution_id, project_id) REFERENCES workflow_executions (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE INDEX tasks_by_project ON tasks (project_id, state);

CREATE INDEX task_plans_by_task ON task_plans (task_id);

CREATE INDEX runs_by_task ON runs (task_id);

CREATE UNIQUE INDEX one_active_attempt_per_run ON run_attempts (run_id) WHERE state = 'active';

CREATE INDEX run_attempts_by_controller ON run_attempts (controller_instance_id);

CREATE TABLE threads (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'thr_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  kind TEXT NOT NULL REFERENCES vocab_thread_kind (word),
  owner_actor_id TEXT REFERENCES actors (id),
  task_id TEXT,
  execution_id TEXT,
  node_key TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK (
    (kind = 'coordinator' AND owner_actor_id IS NOT NULL AND task_id IS NULL AND execution_id IS NULL AND node_key IS NULL)
    OR (kind = 'task' AND owner_actor_id IS NULL AND task_id IS NOT NULL AND execution_id IS NULL AND node_key IS NULL)
    OR (kind = 'step' AND owner_actor_id IS NULL AND task_id IS NOT NULL AND execution_id IS NOT NULL AND node_key IS NOT NULL)
  ),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  FOREIGN KEY (execution_id, project_id) REFERENCES workflow_executions (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE user_inputs (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 6) = 'input_' AND length(id) = 38 AND substr(id, 7) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  thread_id TEXT NOT NULL,
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  command_id TEXT NOT NULL UNIQUE CHECK (substr(command_id, 1, 4) = 'cmd_' AND length(command_id) = 36 AND substr(command_id, 5) NOT GLOB '*[^0-9a-f]*'),
  disposition TEXT NOT NULL REFERENCES vocab_input_disposition (word),
  body TEXT NOT NULL,
  author_actor_id TEXT NOT NULL REFERENCES actors (id),
  state TEXT NOT NULL REFERENCES vocab_user_input_state (word),
  superseded_by_input_id TEXT,
  accepted_at TEXT NOT NULL CHECK (accepted_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (thread_id, sequence),
  CHECK ((state = 'superseded') = (superseded_by_input_id IS NOT NULL)),
  FOREIGN KEY (thread_id, project_id) REFERENCES threads (id, project_id),
  FOREIGN KEY (superseded_by_input_id, project_id) REFERENCES user_inputs (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE turn_deliveries (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'turn_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  thread_id TEXT NOT NULL,
  provider_session_id TEXT NOT NULL,
  node_attempt_id TEXT,
  controller_generation INTEGER NOT NULL CHECK (controller_generation >= 1),
  brief_artifact_id TEXT,
  model TEXT,
  effort TEXT,
  usage TEXT CHECK (json_valid(usage)),
  stop_reason TEXT,
  error_class TEXT,
  state TEXT NOT NULL REFERENCES vocab_turn_delivery_state (word),
  requested_at TEXT NOT NULL CHECK (requested_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  delivered_at TEXT CHECK (delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1), prompt TEXT,
  FOREIGN KEY (thread_id, project_id) REFERENCES threads (id, project_id),
  FOREIGN KEY (provider_session_id, project_id) REFERENCES provider_sessions (id, project_id),
  FOREIGN KEY (node_attempt_id, project_id) REFERENCES node_attempts (id, project_id),
  FOREIGN KEY (brief_artifact_id, project_id) REFERENCES artifacts (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE turn_delivery_inputs (
  project_id TEXT NOT NULL REFERENCES projects (id),
  delivery_id TEXT NOT NULL,
  user_input_id TEXT NOT NULL,
  position INTEGER NOT NULL CHECK (position >= 1),
  PRIMARY KEY (delivery_id, user_input_id),
  FOREIGN KEY (delivery_id, project_id) REFERENCES turn_deliveries (id, project_id),
  FOREIGN KEY (user_input_id, project_id) REFERENCES user_inputs (id, project_id)
) STRICT;

CREATE TABLE thread_items (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'item_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  thread_id TEXT NOT NULL,
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  kind TEXT NOT NULL REFERENCES vocab_thread_item_kind (word),
  user_input_id TEXT,
  delivery_id TEXT,
  provider_session_id TEXT,
  tool_call_id TEXT,
  content TEXT NOT NULL CHECK (json_valid(content)),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (thread_id, sequence),
  CHECK ((kind = 'user_message') = (user_input_id IS NOT NULL)),
  CHECK ((kind = 'tool_call') = (tool_call_id IS NOT NULL)),
  FOREIGN KEY (thread_id, project_id) REFERENCES threads (id, project_id),
  FOREIGN KEY (user_input_id, project_id) REFERENCES user_inputs (id, project_id),
  FOREIGN KEY (delivery_id, project_id) REFERENCES turn_deliveries (id, project_id),
  FOREIGN KEY (provider_session_id, project_id) REFERENCES provider_sessions (id, project_id)
) STRICT;

CREATE INDEX threads_by_project ON threads (project_id);

CREATE UNIQUE INDEX one_coordinator_thread_per_owner ON threads (project_id, owner_actor_id) WHERE kind = 'coordinator';

CREATE UNIQUE INDEX one_thread_per_task ON threads (task_id) WHERE kind = 'task';

CREATE UNIQUE INDEX one_thread_per_step ON threads (execution_id, node_key) WHERE kind = 'step';

CREATE INDEX user_inputs_queued ON user_inputs (thread_id, sequence) WHERE state = 'queued';

CREATE UNIQUE INDEX one_active_turn_per_thread ON turn_deliveries (thread_id) WHERE state IN ('pending', 'delivered');

CREATE INDEX turn_deliveries_by_session ON turn_deliveries (provider_session_id);

CREATE TABLE agent_installations (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'inst_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  device_id TEXT NOT NULL REFERENCES devices (id),
  agent_id TEXT NOT NULL,
  agent_version TEXT,
  adapter_version TEXT,
  protocol_version INTEGER,
  status TEXT NOT NULL REFERENCES vocab_installation_status (word),
  capabilities TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(capabilities)),
  probed_at TEXT NOT NULL CHECK (probed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE principals (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'prin_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  agent_id TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES devices (id),
  subject_hint TEXT NOT NULL,
  auth_mode TEXT NOT NULL REFERENCES vocab_auth_mode (word),
  observed_at TEXT NOT NULL CHECK (observed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
, account_id TEXT REFERENCES agent_accounts (id)) STRICT;

CREATE TABLE account_statuses (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'acct_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  principal_id TEXT NOT NULL REFERENCES principals (id),
  state TEXT NOT NULL REFERENCES vocab_account_state (word),
  windows TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(windows)),
  source TEXT NOT NULL REFERENCES vocab_account_status_source (word),
  observed_at TEXT NOT NULL CHECK (observed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE provider_sessions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'sess_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  thread_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  model TEXT,
  effort TEXT,
  config TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(config)),
  principal_id TEXT REFERENCES principals (id),
  installation_id TEXT REFERENCES agent_installations (id),
  external_session_id TEXT,
  run_attempt_id TEXT,
  controller_generation INTEGER CHECK (controller_generation >= 1),
  brief_artifact_id TEXT,
  state TEXT NOT NULL REFERENCES vocab_provider_session_state (word),
  superseded_by_session_id TEXT,
  last_event_sequence INTEGER NOT NULL DEFAULT 0 CHECK (last_event_sequence >= 0),
  started_at TEXT NOT NULL CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1), account_id TEXT REFERENCES agent_accounts (id),
  CHECK ((state = 'superseded') = (superseded_by_session_id IS NOT NULL)),
  FOREIGN KEY (thread_id, project_id) REFERENCES threads (id, project_id),
  FOREIGN KEY (run_attempt_id, project_id) REFERENCES run_attempts (id, project_id),
  FOREIGN KEY (brief_artifact_id, project_id) REFERENCES artifacts (id, project_id),
  FOREIGN KEY (superseded_by_session_id, project_id) REFERENCES provider_sessions (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE node_attempts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'natt_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  node_id TEXT NOT NULL,
  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
  run_attempt_id TEXT NOT NULL,
  controller_generation INTEGER NOT NULL CHECK (controller_generation >= 1),
  provider_session_id TEXT,
  state TEXT NOT NULL REFERENCES vocab_node_attempt_state (word),
  hold_reason TEXT REFERENCES vocab_hold_reason (word),
  input TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(input)),
  output TEXT CHECK (json_valid(output)),
  output_artifact_id TEXT,
  error_class TEXT,
  admitted_at TEXT NOT NULL CHECK (admitted_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  started_at TEXT CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (node_id, attempt_number),
  CHECK ((state = 'held') = (hold_reason IS NOT NULL)),
  FOREIGN KEY (node_id, project_id) REFERENCES nodes (id, project_id),
  FOREIGN KEY (run_attempt_id, project_id) REFERENCES run_attempts (id, project_id),
  FOREIGN KEY (provider_session_id, project_id) REFERENCES provider_sessions (id, project_id),
  FOREIGN KEY (output_artifact_id, project_id) REFERENCES artifacts (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE workspace_snapshots (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'snap_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  workspace_id TEXT NOT NULL,
  node_attempt_id TEXT,
  commit_sha TEXT CHECK (length(commit_sha) IN (40, 64) AND commit_sha NOT GLOB '*[^0-9a-f]*'),
  tree_sha TEXT CHECK (length(tree_sha) IN (40, 64) AND tree_sha NOT GLOB '*[^0-9a-f]*'),
  reason TEXT NOT NULL REFERENCES vocab_snapshot_reason (word),
  taken_at TEXT NOT NULL CHECK (taken_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  CHECK (commit_sha IS NOT NULL OR tree_sha IS NOT NULL),
  FOREIGN KEY (workspace_id, project_id) REFERENCES workspaces (id, project_id),
  FOREIGN KEY (node_attempt_id, project_id) REFERENCES node_attempts (id, project_id)
) STRICT;

CREATE INDEX account_statuses_by_principal ON account_statuses (principal_id, observed_at);

CREATE INDEX provider_sessions_by_thread ON provider_sessions (thread_id);

CREATE INDEX provider_sessions_by_run_attempt ON provider_sessions (run_attempt_id);

CREATE UNIQUE INDEX one_unfinished_attempt_per_node ON node_attempts (node_id) WHERE state NOT IN ('succeeded', 'failed', 'cancelled', 'superseded');

CREATE INDEX node_attempts_by_session ON node_attempts (provider_session_id);

CREATE INDEX node_attempts_by_run_attempt ON node_attempts (run_attempt_id);

CREATE INDEX workspace_snapshots_by_workspace ON workspace_snapshots (workspace_id, taken_at);

CREATE INDEX workspace_snapshots_by_attempt ON workspace_snapshots (node_attempt_id);

CREATE TABLE permission_requests (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'perm_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  provider_session_id TEXT NOT NULL,
  node_attempt_id TEXT,
  tool_call_id TEXT NOT NULL,
  tool_kind TEXT NOT NULL REFERENCES vocab_tool_kind (word),
  title TEXT NOT NULL,
  raw_input TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(raw_input)),
  options TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(options)),
  action_digest TEXT NOT NULL,
  state TEXT NOT NULL REFERENCES vocab_permission_request_state (word),
  received_at TEXT NOT NULL CHECK (received_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  FOREIGN KEY (provider_session_id, project_id) REFERENCES provider_sessions (id, project_id),
  FOREIGN KEY (node_attempt_id, project_id) REFERENCES node_attempts (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE attention_requests (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'attn_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT,
  node_attempt_id TEXT,
  permission_request_id TEXT,
  kind TEXT NOT NULL REFERENCES vocab_attention_kind (word),
  addressee_actor_id TEXT REFERENCES actors (id),
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  action_digest TEXT,
  policy_id TEXT,
  state TEXT NOT NULL REFERENCES vocab_attention_state (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  expires_at TEXT CHECK (expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  answered_at TEXT CHECK (answered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK ((kind = 'permission') = (permission_request_id IS NOT NULL)),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  FOREIGN KEY (node_attempt_id, project_id) REFERENCES node_attempts (id, project_id),
  FOREIGN KEY (permission_request_id, project_id) REFERENCES permission_requests (id, project_id),
  FOREIGN KEY (policy_id, project_id) REFERENCES policies (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE findings (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'find_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  review_attempt_id TEXT NOT NULL,
  severity TEXT NOT NULL REFERENCES vocab_finding_severity (word),
  location TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(location)),
  claim TEXT NOT NULL,
  confidence REAL CHECK (confidence >= 0 AND confidence <= 1),
  state TEXT NOT NULL REFERENCES vocab_finding_state (word),
  settled_by_actor_id TEXT REFERENCES actors (id),
  settled_in_attempt_id TEXT,
  response TEXT,
  repeats_finding_id TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  settled_at TEXT CHECK (settled_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK ((state = 'open') = (settled_at IS NULL)),
  FOREIGN KEY (review_attempt_id, project_id) REFERENCES node_attempts (id, project_id),
  FOREIGN KEY (settled_in_attempt_id, project_id) REFERENCES node_attempts (id, project_id),
  FOREIGN KEY (repeats_finding_id, project_id) REFERENCES findings (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE decisions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'dec_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  permission_request_id TEXT,
  attention_request_id TEXT,
  finding_id TEXT,
  outcome TEXT NOT NULL REFERENCES vocab_decision_outcome (word),
  scope TEXT REFERENCES vocab_decision_scope (word),
  agent_option_id TEXT,
  reason TEXT,
  decided_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  decided_by_session_id TEXT,
  rule TEXT CHECK (json_valid(rule)),
  policy_id TEXT,
  action_digest TEXT,
  supersedes_decision_id TEXT,
  decided_at TEXT NOT NULL CHECK (decided_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  consumed_at TEXT CHECK (consumed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  CHECK ((permission_request_id IS NOT NULL) + (attention_request_id IS NOT NULL) + (finding_id IS NOT NULL) = 1),
  CHECK ((outcome IN ('allow', 'reject')) = (scope IS NOT NULL)),
  CHECK (agent_option_id IS NULL OR permission_request_id IS NOT NULL),
  FOREIGN KEY (permission_request_id, project_id) REFERENCES permission_requests (id, project_id),
  FOREIGN KEY (attention_request_id, project_id) REFERENCES attention_requests (id, project_id),
  FOREIGN KEY (finding_id, project_id) REFERENCES findings (id, project_id),
  FOREIGN KEY (decided_by_session_id, project_id) REFERENCES provider_sessions (id, project_id),
  FOREIGN KEY (policy_id, project_id) REFERENCES policies (id, project_id),
  FOREIGN KEY (supersedes_decision_id, project_id) REFERENCES decisions (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE INDEX permission_requests_open ON permission_requests (provider_session_id) WHERE state = 'open';

CREATE INDEX attention_requests_by_project ON attention_requests (project_id, state);

CREATE INDEX attention_requests_by_task ON attention_requests (task_id);

CREATE INDEX findings_by_review ON findings (review_attempt_id);

CREATE INDEX findings_open ON findings (project_id) WHERE state = 'open';

CREATE INDEX findings_by_repeated ON findings (repeats_finding_id);

CREATE INDEX decisions_by_permission_request ON decisions (permission_request_id);

CREATE INDEX decisions_by_attention_request ON decisions (attention_request_id);

CREATE INDEX decisions_by_finding ON decisions (finding_id);

CREATE TABLE change_sets (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'chg_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT NOT NULL,
  run_id TEXT NOT NULL,
  state TEXT NOT NULL REFERENCES vocab_change_set_state (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  FOREIGN KEY (run_id, project_id) REFERENCES runs (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE TABLE repository_changes (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'rchg_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  change_set_id TEXT NOT NULL,
  binding_id TEXT NOT NULL,
  workspace_id TEXT,
  base_commit TEXT CHECK (length(base_commit) IN (40, 64) AND base_commit NOT GLOB '*[^0-9a-f]*'),
  head_commit TEXT CHECK (length(head_commit) IN (40, 64) AND head_commit NOT GLOB '*[^0-9a-f]*'),
  branch TEXT NOT NULL,
  patch_artifact_id TEXT,
  pull_request_url TEXT,
  pull_request_state TEXT NOT NULL DEFAULT 'none' REFERENCES vocab_pull_request_state (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (change_set_id, binding_id),
  FOREIGN KEY (change_set_id, project_id) REFERENCES change_sets (id, project_id),
  FOREIGN KEY (binding_id, project_id) REFERENCES repository_bindings (id, project_id),
  FOREIGN KEY (workspace_id, project_id) REFERENCES workspaces (id, project_id),
  FOREIGN KEY (patch_artifact_id, project_id) REFERENCES artifacts (id, project_id)
) STRICT;

CREATE TABLE work_items (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'work_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT REFERENCES projects (id),
  kind TEXT NOT NULL,
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  state TEXT NOT NULL REFERENCES vocab_work_item_state (word),
  run_attempt_id TEXT,
  controller_generation INTEGER CHECK (controller_generation >= 1),
  claimed_by_instance_id TEXT REFERENCES runtime_instances (id),
  lease_expires_at TEXT CHECK (lease_expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at TEXT NOT NULL CHECK (available_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  last_error TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK ((state = 'claimed') = (claimed_by_instance_id IS NOT NULL AND lease_expires_at IS NOT NULL)),
  CHECK (run_attempt_id IS NULL OR project_id IS NOT NULL),
  FOREIGN KEY (run_attempt_id, project_id) REFERENCES run_attempts (id, project_id)
) STRICT;

CREATE TABLE mutation_receipts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'mut_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT REFERENCES projects (id),
  work_item_id TEXT NOT NULL REFERENCES work_items (id),
  target TEXT NOT NULL,
  operation TEXT NOT NULL,
  idempotency_key TEXT,
  state TEXT NOT NULL REFERENCES vocab_mutation_state (word),
  request TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(request)),
  response TEXT CHECK (json_valid(response)),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  confirmed_at TEXT CHECK (confirmed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE observations (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'obs_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT REFERENCES projects (id),
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  source TEXT NOT NULL,
  observed_at TEXT NOT NULL CHECK (observed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE INDEX change_sets_by_task ON change_sets (task_id);

CREATE INDEX work_items_ready ON work_items (available_at) WHERE state = 'pending';

CREATE INDEX work_items_claimed ON work_items (lease_expires_at) WHERE state = 'claimed';

CREATE INDEX mutation_receipts_by_work_item ON mutation_receipts (work_item_id);

CREATE INDEX observations_by_subject ON observations (subject_type, subject_id, observed_at);

CREATE TABLE record_events (
  sequence INTEGER PRIMARY KEY AUTOINCREMENT,
  id TEXT NOT NULL UNIQUE CHECK (substr(id, 1, 4) = 'evt_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT REFERENCES projects (id),
  aggregate_type TEXT NOT NULL REFERENCES vocab_aggregate_type (word),
  aggregate_id TEXT NOT NULL,
  aggregate_revision INTEGER NOT NULL CHECK (aggregate_revision >= 1),
  type TEXT NOT NULL CHECK (type GLOB '[a-z]*.[a-z]*' AND type NOT GLOB '*[^a-z_.]*'),
  schema_version INTEGER NOT NULL DEFAULT 1 CHECK (schema_version >= 1),
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  actor_id TEXT NOT NULL REFERENCES actors (id),
  command_id TEXT CHECK (substr(command_id, 1, 4) = 'cmd_' AND length(command_id) = 36 AND substr(command_id, 5) NOT GLOB '*[^0-9a-f]*'),
  occurred_at TEXT NOT NULL CHECK (occurred_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE change_log (
  cursor INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT REFERENCES projects (id),
  aggregate_type TEXT NOT NULL REFERENCES vocab_aggregate_type (word),
  aggregate_id TEXT NOT NULL,
  aggregate_revision INTEGER NOT NULL CHECK (aggregate_revision >= 1),
  changed_at TEXT NOT NULL CHECK (changed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE command_receipts (
  actor_id TEXT NOT NULL REFERENCES actors (id),
  command_id TEXT NOT NULL CHECK (substr(command_id, 1, 4) = 'cmd_' AND length(command_id) = 36 AND substr(command_id, 5) NOT GLOB '*[^0-9a-f]*'),
  on_behalf_of_actor_id TEXT REFERENCES actors (id),
  command_type TEXT NOT NULL,
  schema_version INTEGER NOT NULL CHECK (schema_version >= 1),
  payload_digest TEXT NOT NULL CHECK (length(payload_digest) = 64 AND payload_digest NOT GLOB '*[^0-9a-f]*'),
  device_id TEXT NOT NULL REFERENCES devices (id),
  project_id TEXT REFERENCES projects (id),
  aggregate_id TEXT,
  result TEXT NOT NULL CHECK (json_valid(result)),
  received_at TEXT NOT NULL CHECK (received_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  completed_at TEXT NOT NULL CHECK (completed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (actor_id, command_id)
) STRICT;

CREATE INDEX record_events_by_aggregate ON record_events (aggregate_type, aggregate_id, sequence);

CREATE INDEX record_events_by_project ON record_events (project_id, sequence);

CREATE INDEX change_log_by_project ON change_log (project_id, cursor);

CREATE UNIQUE INDEX one_item_per_tool_call ON thread_items (provider_session_id, tool_call_id) WHERE tool_call_id IS NOT NULL;

CREATE TABLE "processes" (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'proc_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT REFERENCES projects (id),
  device_id TEXT NOT NULL REFERENCES devices (id),
  runtime_instance_id TEXT NOT NULL REFERENCES runtime_instances (id),
  provider_session_id TEXT,
  run_attempt_id TEXT,
  node_attempt_id TEXT,
  purpose TEXT NOT NULL REFERENCES vocab_process_purpose (word),
  executable TEXT NOT NULL,
  executable_version TEXT,
  pid INTEGER CHECK (pid > 0),
  process_group_id INTEGER CHECK (process_group_id > 0),
  os_started_at TEXT CHECK (os_started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  args_redacted TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(args_redacted)),
  environment_digest TEXT,
  controller_generation INTEGER CHECK (controller_generation >= 1),
  state TEXT NOT NULL REFERENCES vocab_process_state (word),
  launched_at TEXT NOT NULL CHECK (launched_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  exit_code INTEGER,
  signal TEXT,
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK (state IN ('launching', 'unknown') OR pid IS NOT NULL),
  CHECK ((provider_session_id IS NULL AND run_attempt_id IS NULL AND node_attempt_id IS NULL) OR project_id IS NOT NULL),
  FOREIGN KEY (provider_session_id, project_id) REFERENCES provider_sessions (id, project_id),
  FOREIGN KEY (run_attempt_id, project_id) REFERENCES run_attempts (id, project_id),
  FOREIGN KEY (node_attempt_id, project_id) REFERENCES node_attempts (id, project_id)
) STRICT;

CREATE INDEX processes_by_session ON processes (provider_session_id);

CREATE INDEX processes_live ON processes (runtime_instance_id) WHERE state IN ('launching', 'running');

CREATE UNIQUE INDEX one_live_session_per_thread ON provider_sessions (thread_id) WHERE state IN ('active', 'waiting_approval', 'cancelling');

CREATE UNIQUE INDEX runs_by_plan ON runs (plan_id) WHERE plan_id IS NOT NULL;

CREATE TABLE connections (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'conn_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  device_id TEXT NOT NULL REFERENCES devices (id),
  product TEXT NOT NULL REFERENCES vocab_connection_product (word),
  web_url TEXT NOT NULL,
  api_url TEXT NOT NULL,
  account_id TEXT NOT NULL,
  account_login TEXT NOT NULL,
  account_name TEXT,
  auth TEXT NOT NULL REFERENCES vocab_connection_auth (word),
  credential_ref TEXT NOT NULL,
  expires_at TEXT CHECK (expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  state TEXT NOT NULL REFERENCES vocab_connection_state (word),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE UNIQUE INDEX one_connection_per_account ON connections (device_id, product, web_url, account_id) WHERE state <> 'removed';

CREATE TABLE external_links (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 6) = 'xlink_' AND length(id) = 38 AND substr(id, 7) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT NOT NULL,
  connection_id TEXT REFERENCES connections (id),
  product TEXT NOT NULL REFERENCES vocab_connection_product (word),
  kind TEXT NOT NULL REFERENCES vocab_external_kind (word),
  external_id TEXT NOT NULL,
  ref TEXT NOT NULL,
  key TEXT NOT NULL,
  url TEXT NOT NULL,
  snapshot TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(snapshot)),
  listening INTEGER NOT NULL DEFAULT 0 CHECK (listening IN (0, 1)),
  cursor TEXT,
  polled_at TEXT CHECK (polled_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (task_id, kind, product, external_id),
  FOREIGN KEY (task_id, project_id) REFERENCES tasks (id, project_id),
  UNIQUE (id, project_id)
) STRICT;

CREATE INDEX external_links_by_task ON external_links (task_id);

CREATE INDEX external_links_listening ON external_links (listening) WHERE listening = 1;

CREATE UNIQUE INDEX observations_once ON observations (subject_type, subject_id, kind, json_extract(payload, '$.id')) WHERE json_extract(payload, '$.id') IS NOT NULL;

CREATE TABLE model_preferences (
  agent_id TEXT NOT NULL,
  model TEXT NOT NULL,
  effort TEXT NOT NULL,
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (agent_id, model)
) STRICT;

CREATE TABLE agent_accounts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'acc_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  agent_id TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES devices (id),
  name TEXT NOT NULL CHECK (length(trim(name)) > 0),
  home TEXT,
  position INTEGER NOT NULL CHECK (position >= 0),
  adopted_from TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  removed_at TEXT CHECK (removed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE UNIQUE INDEX agent_accounts_usual ON agent_accounts (device_id, agent_id) WHERE home IS NULL AND removed_at IS NULL;

CREATE UNIQUE INDEX agent_accounts_by_home ON agent_accounts (device_id, home) WHERE home IS NOT NULL AND removed_at IS NULL;
